In [6]:
import pandas as pd

df=pd.read_csv("jems.csv")
df.set_index("Film", inplace=True)
df.reset_index()

,Film,Year,Years lapse,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
0,Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
1,From Russia With Love,1963,1.0,Sean Connery,2,11,16,27,543.8,78.9,...,0,0,0,16.0,3,Bentley,115,April,PG,0
2,Goldfinger,1964,1.0,Sean Connery,3,9,68,77,820.4,124.9,...,0,1,1,12.0,5,Aston Martin,110,September,PG,1
3,Thunderball,1965,1.0,Sean Connery,4,20,90,110,848.1,141.2,...,0,1,1,14.5,5,Lincoln,130,December,PG,0
4,You Only Live Twice,1967,2.0,Sean Connery,5,21,175,196,514.2,101.0,...,0,0,0,9.5,4,Toyota,117,June,PG,0
5,On Her Majesty's Secret Service,1969,2.0,George Lazenby,1,5,37,42,291.5,64.6,...,0,0,0,9.5,3,Aston Martin,142,December,PG,2
6,Diamonds Are Forever,1971,2.0,Sean Connery,6,7,42,49,442.5,116.0,...,0,1,0,6.0,5,Ford,120,December,PG,1
7,Live and Let Die,1973,2.0,Roger Moore,1,8,5,13,460.3,126.4,...,0,1,0,15.5,3,Chevrolet,121,June,PG,1
8,The Man with the Golden Gun,1974,1.0,Roger Moore,2,1,5,6,334.0,98.5,...,0,0,0,11.5,4,AMC,125,December,PG,2
9,The Spy Who Loved Me,1977,3.0,Roger Moore,3,31,116,147,533.0,185.4,...,0,3,0,7.0,3,Lotus,125,July,PG,1
10,Moonraker,1979,2.0,Roger Moore,4,12,69,81,535.0,210.3,...,0,1,0,7.0,4,Bentley,126,June,PG,1
11,For Your Eyes Only,1981,2.0,Roger Moore,5,18,36,54,449.4,194.9,...,0,1,0,10.5,3,Lotus,127,June,PG,2
12,Octopussy,1983,2.0,Roger Moore,6,15,43,58,373.8,183.7,...,0,0,0,14.5,3,Mercedes-Benz,131,June,PG,1
13,A View to a Kill,1985,2.0,Roger Moore,7,5,57,62,275.2,152.4,...,0,0,0,14.5,4,Renault,131,May,PG,2
14,The Living Daylights,1987,2.0,Timothy Dalton,1,13,29,42,313.5,191.2,...,0,0,0,5.5,2,Aston Martin,130,June,PG,1
15,Licence to Kill,1989,2.0,Timothy Dalton,2,10,13,23,250.9,156.2,...,0,0,0,4.0,2,Lincoln,133,July,R,1
16,GoldenEye,1995,6.0,Pierce Brosnan,1,47,25,72,518.5,351.9,...,0,0,0,8.0,3,BMW,130,November,PG-13,1
17,Tomorrow Never Dies,1997,2.0,Pierce Brosnan,2,30,24,54,463.2,338.9,...,0,0,0,22.0,3,BMW,119,December,PG-13,1
18,The World is Not Enough,1999,2.0,Pierce Brosnan,3,27,43,70,439.5,361.8,...,0,0,0,12.5,3,BMW,128,November,PG-13,2
19,Die Another Day,2002,3.0,Pierce Brosnan,4,31,20,51,465.4,431.9,...,0,0,0,5.5,3,Aston Martin,133,November,PG-13,1
20,Casino Royale,2006,4.0,Daniel Craig,1,11,11,22,581.5,594.2,...,0,0,0,26.0,2,Aston Martin,144,November,PG-13,1
21,Quantum of Solace,2008,2.0,Daniel Craig,2,16,15,31,514.2,576.0,...,0,0,0,18.0,2,Aston Martin,106,November,PG-13,0
22,Skyfall,2012,4.0,Daniel Craig,3,26,23,49,879.8,1108.6,...,1,5,2,16.0,2,Aston Martin,143,November,PG-13,1

In [20]:
import pandas as pd

df=pd.read_csv("jems.csv")
df.set_index("Year", inplace=True)
df.reset_index()

,Year,Film,Years lapse,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
0,1962,Dr. No,NaN,Sean Connery,1,4,8,12,448.8,59.5,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
1,1963,From Russia With Love,1.0,Sean Connery,2,11,16,27,543.8,78.9,...,0,0,0,16.0,3,Bentley,115,April,PG,0
2,1964,Goldfinger,1.0,Sean Connery,3,9,68,77,820.4,124.9,...,0,1,1,12.0,5,Aston Martin,110,September,PG,1
3,1965,Thunderball,1.0,Sean Connery,4,20,90,110,848.1,141.2,...,0,1,1,14.5,5,Lincoln,130,December,PG,0
4,1967,You Only Live Twice,2.0,Sean Connery,5,21,175,196,514.2,101.0,...,0,0,0,9.5,4,Toyota,117,June,PG,0
5,1969,On Her Majesty's Secret Service,2.0,George Lazenby,1,5,37,42,291.5,64.6,...,0,0,0,9.5,3,Aston Martin,142,December,PG,2
6,1971,Diamonds Are Forever,2.0,Sean Connery,6,7,42,49,442.5,116.0,...,0,1,0,6.0,5,Ford,120,December,PG,1
7,1973,Live and Let Die,2.0,Roger Moore,1,8,5,13,460.3,126.4,...,0,1,0,15.5,3,Chevrolet,121,June,PG,1
8,1974,The Man with the Golden Gun,1.0,Roger Moore,2,1,5,6,334.0,98.5,...,0,0,0,11.5,4,AMC,125,December,PG,2
9,1977,The Spy Who Loved Me,3.0,Roger Moore,3,31,116,147,533.0,185.4,...,0,3,0,7.0,3,Lotus,125,July,PG,1
10,1979,Moonraker,2.0,Roger Moore,4,12,69,81,535.0,210.3,...,0,1,0,7.0,4,Bentley,126,June,PG,1
11,1981,For Your Eyes Only,2.0,Roger Moore,5,18,36,54,449.4,194.9,...,0,1,0,10.5,3,Lotus,127,June,PG,2
12,1983,Octopussy,2.0,Roger Moore,6,15,43,58,373.8,183.7,...,0,0,0,14.5,3,Mercedes-Benz,131,June,PG,1
13,1985,A View to a Kill,2.0,Roger Moore,7,5,57,62,275.2,152.4,...,0,0,0,14.5,4,Renault,131,May,PG,2
14,1987,The Living Daylights,2.0,Timothy Dalton,1,13,29,42,313.5,191.2,...,0,0,0,5.5,2,Aston Martin,130,June,PG,1
15,1989,Licence to Kill,2.0,Timothy Dalton,2,10,13,23,250.9,156.2,...,0,0,0,4.0,2,Lincoln,133,July,R,1
16,1995,GoldenEye,6.0,Pierce Brosnan,1,47,25,72,518.5,351.9,...,0,0,0,8.0,3,BMW,130,November,PG-13,1
17,1997,Tomorrow Never Dies,2.0,Pierce Brosnan,2,30,24,54,463.2,338.9,...,0,0,0,22.0,3,BMW,119,December,PG-13,1
18,1999,The World is Not Enough,2.0,Pierce Brosnan,3,27,43,70,439.5,361.8,...,0,0,0,12.5,3,BMW,128,November,PG-13,2
19,2002,Die Another Day,3.0,Pierce Brosnan,4,31,20,51,465.4,431.9,...,0,0,0,5.5,3,Aston Martin,133,November,PG-13,1
20,2006,Casino Royale,4.0,Daniel Craig,1,11,11,22,581.5,594.2,...,0,0,0,26.0,2,Aston Martin,144,November,PG-13,1
21,2008,Quantum of Solace,2.0,Daniel Craig,2,16,15,31,514.2,576.0,...,0,0,0,18.0,2,Aston Martin,106,November,PG-13,0
22,2012,Skyfall,4.0,Daniel Craig,3,26,23,49,879.8,1108.6,...,1,5,2,16.0,2,Aston Martin,143,November,PG-13,1

,Year,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,Adjusted budget,Actual budget,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
0,1962,Sean Connery,1,4,8,12,448.8,59.5,7.0,1.1,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
1,1963,Sean Connery,2,11,16,27,543.8,78.9,12.6,2.0,...,0,0,0,16.0,3,Bentley,115,April,PG,0
2,1964,Sean Connery,3,9,68,77,820.4,124.9,18.6,3.0,...,0,1,1,12.0,5,Aston Martin,110,September,PG,1
3,1965,Sean Connery,4,20,90,110,848.1,141.2,41.9,6.8,...,0,1,1,14.5,5,Lincoln,130,December,PG,0
4,1967,Sean Connery,5,21,175,196,514.2,101.0,59.9,10.3,...,0,0,0,9.5,4,Toyota,117,June,PG,0
5,1969,George Lazenby,1,5,37,42,291.5,64.6,37.3,7.0,...,0,0,0,9.5,3,Aston Martin,142,December,PG,2
6,1971,Sean Connery,6,7,42,49,442.5,116.0,34.7,7.2,...,0,1,0,6.0,5,Ford,120,December,PG,1
7,1973,Roger Moore,1,8,5,13,460.3,126.4,30.8,7.0,...,0,1,0,15.5,3,Chevrolet,121,June,PG,1
8,1974,Roger Moore,2,1,5,6,334.0,98.5,27.7,7.0,...,0,0,0,11.5,4,AMC,125,December,PG,2
9,1977,Roger Moore,3,31,116,147,533.0,185.4,45.1,14.0,...,0,3,0,7.0,3,Lotus,125,July,PG,1
10,1979,Roger Moore,4,12,69,81,535.0,210.3,91.5,34.0,...,0,1,0,7.0,4,Bentley,126,June,PG,1
11,1981,Roger Moore,5,18,36,54,449.4,194.9,60.2,28.0,...,0,1,0,10.5,3,Lotus,127,June,PG,2
12,1983,Roger Moore,6,15,43,58,373.8,183.7,53.9,27.5,...,0,0,0,14.5,3,Mercedes-Benz,131,June,PG,1
13,1985,Roger Moore,7,5,57,62,275.2,152.4,54.5,30.0,...,0,0,0,14.5,4,Renault,131,May,PG,2
14,1987,Timothy Dalton,1,13,29,42,313.5,191.2,68.8,40.0,...,0,0,0,5.5,2,Aston Martin,130,June,PG,1
15,1989,Timothy Dalton,2,10,13,23,250.9,156.2,56.7,36.0,...,0,0,0,4.0,2,Lincoln,133,July,R,1
16,1995,Pierce Brosnan,1,47,25,72,518.5,351.9,76.9,60.0,...,0,0,0,8.0,3,BMW,130,November,PG-13,1
17,1997,Pierce Brosnan,2,30,24,54,463.2,338.9,133.9,110.0,...,0,0,0,22.0,3,BMW,119,December,PG-13,1
18,1999,Pierce Brosnan,3,27,43,70,439.5,361.8,158.3,135.0,...,0,0,0,12.5,3,BMW,128,November,PG-13,2
19,2002,Pierce Brosnan,4,31,20,51,465.4,431.9,154.2,142.0,...,0,0,0,5.5,3,Aston Martin,133,November,PG-13,1
20,2006,Daniel Craig,1,11,11,22,581.5,594.2,145.3,150.0,...,0,0,0,26.0,2,Aston Martin,144,November,PG-13,1
21,2008,Daniel Craig,2,16,15,31,514.2,576.0,181.4,200.0,...,0,0,0,18.0,2,Aston Martin,106,November,PG-13,0
22,2012,Daniel Craig,3,26,23,49,879.8,1108.6,158.1,200.0,...,1,5,2,16.0,2,Aston Martin,143,November,PG-13,1

In [19]:
df.set_index("Bond actor",inplace=True)
df

KeyError: 'Bond actor'